import axios from 'axios';

export default {
    config: {
        name: 'carbon',
        aliases: ['codeimage'],
        author: 'Broken_vzn',
        version: '1.0',
        shortDescription: 'Generate code image',
        category: 'fun',
        coolDown: 10,
        role: 0,
        guide: { en: '{prefix}carbon <code>' },
    },

    async onStart({ args, reply, message, quoted, prefix, React }) {
        React('🖼️');

        let code = '';
        if (quoted?.message?.conversation) code = quoted.message.conversation;
        else if (quoted?.message?.extendedTextMessage?.text) code = quoted.message.extendedTextMessage.text;
        else if (args.length) code = args.join(' ');

        if (!code) return reply(`Reply to a message with code or provide code.\nUsage: ${prefix}carbon <code>`);

        try {
            const encoded = encodeURIComponent(code);
            const url = `https://carbonara.solopace.dev/api/cook?code=${encoded}&theme=monokai&language=javascript&size=2x`;
            const { data } = await axios.get(url, { responseType: 'arraybuffer', timeout: 30000 });
            const buffer = Buffer.from(data);

            reply({
                image: buffer,
                caption: `🖼️ *Carbon Code Image*\n━━━━━━━━━━━━━━━━━━━━\nGenerated by ${prefix}carbon\n━━━━━━━━━━━━━━━━━━━━`,
            });
        } catch {
            reply(`❌ Failed to generate code image.`);
        }
    },
};
